//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThueSach
    {
        public int MaChiTiet { get; set; }
        public int MaThueSach { get; set; }
        public int MaSach { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public int DaTra { get; set; }
        public string GhiChu { get; set; }
        public string NguoiChoThue { get; set; }
    
        public virtual Sach Sach { get; set; }
        public virtual ThueSach ThueSach { get; set; }
    }
}
